version: '3.9'
services:
  web:
    build: .
    image: arimelody-home
    container_name: arimelody-home
    ports:
      - 443:443
    volumes:
      - ./certs/arimelody.crt:/etc/nginx/ssl/arimelody.crt
      - ./certs/arimelody.key:/etc/nginx/ssl/arimelody.key
    restart: unless-stopped
